services:
  db:
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - db_data:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:1.7.8
    ports:
      - 8080:80
    restart: always
    environment:
      PS_DEV_MODE: 0
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWORD: prestashop
    volumes:
      - ./prestashop:/var/www/html:cached

volumes:
  db_data:
